<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HandHeld.Host.Core</RootNamespace>
    <AssemblyName>HandHeld.Host.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.6.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.249" />
  </ItemGroup>

</Project>
